const test=require('node:test'),assert=require('node:assert/strict');
const books=require('../keepsake-books.js'),fs=require('node:fs'),vm=require('node:vm');
function storage(data={}){const map=new Map(Object.entries(data).map(([k,v])=>[k,typeof v==='string'?v:JSON.stringify(v)]));return {map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)}}
const fixture=()=>storage({'cw-calendar':[{d:'2026-10-08',title:'Daily',text:'Hello'}],'cw-moon-entries':[{id:'moon',d:'2026-10-07',phase:'Waning Crescent',journal:'Moon notes',practice:'Rest'}],'cw-tarot-entries':[{id:'tarot',d:'2026-10-06',card:'The Star',first:'Hope',journal:'Today',meaning:'Trust'}],'cw-observances':[{wheel:'Samhain',memory:'Family'}],'cw-recipes':[{type:'spell',values:['Light'],labels:['Name'],steps:['One']},{type:'ritual',values:['Rest'],labels:['Name']}],'cw-archive-moon':[{name:'Full Moon',text:'Tradition'}],'cw-archive-wheel':[{name:'Yule',text:'Candles'}],'cw-tarot-journal':'Legacy unsaved draft'});
test('journal combines saved daily, moon and tarot once, in date order, without storage writes',()=>{let s=fixture(),before=[...s.map];let a=books.journal(s);assert.deepEqual(a.map(x=>x.source),['Tarot','Moon','Daily']);assert.match(a[1].text,/Rest/);assert.match(a[0].text,/Trust/);assert.deepEqual([...s.map],before);assert.ok(!a.some(x=>x.text.includes('Legacy')))});
test('grimoire includes celebrations, both recipe types and legacy traditions, and excludes daily reflections',()=>{let s=fixture(),before=[...s.map],b=books.grimoire(s);assert.equal(b.celebrations.length,1);assert.equal(b.recipes.length,2);assert.equal(b.traditions.length,2);assert.ok(!JSON.stringify(b).includes('Moon notes'));assert.deepEqual([...s.map],before)});
test('tarot saves append new dated entries and edits replace the same entry',()=>{let s=storage({'cw-tarot-journal':'old draft'});let a=books.saveTarot(s,{d:'2026-10-08',card:'Star',journal:'One'});books.saveTarot(s,{d:'2026-10-08',card:'Star',journal:'Updated'},a.id);books.saveTarot(s,{d:'2026-10-09',card:'Sun',journal:'Two'});assert.equal(books.readTarot(s).length,2);assert.equal(books.readTarot(s)[1].journal,'Updated');assert.equal(s.getItem('cw-tarot-journal'),'old draft')});
test('invalid dates and corrupt storage fail without changing existing entries',()=>{let s=storage({'cw-tarot-entries':'{bad'}),before=[...s.map];assert.throws(()=>books.saveTarot(s,{d:'2026-10-08',card:'Star'}));assert.deepEqual([...s.map],before);assert.throws(()=>books.saveTarot(storage(),{d:'2026-02-30',card:'Star'}));assert.throws(()=>books.journal(storage({'cw-calendar':{bad:true}})));assert.throws(()=>books.grimoire(storage({'cw-archive-moon':'oops'})))});
test('failed writes do not erase existing Tarot entries',()=>{let s=fixture(),before=[...s.map];s.setItem=()=>{throw Error('Quota')};assert.throws(()=>books.saveTarot(s,{d:'2026-10-08',card:'Moon'}));assert.deepEqual([...s.map],before)});
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
test('Book of Shadows prints on US Letter paper and contains the uncropped cover',()=>{
 assert.match(html,/@page shadows\{size:8.5in 11in;margin:0\.4in\}/);
 assert.match(html,/#traditionsPrint\.print-target\{page:shadows;width:7\.7in!important/);
 assert.match(html,/#traditionsPrint \.book-cover\.shadows-cover\{height:10\.2in!important/);
 assert.match(html,/#traditionsPrint \.shadows-cover img\{[^}]*object-fit:contain/);
 assert.match(html,/#traditionsPrint \.shadows-cover img\.cover-screen\{display:none!important\}/);
 assert.match(html,/#traditionsPrint \.shadows-cover img\.cover-print\{display:block!important\}/);
 assert.match(html,/class="cover-print" src="assets\/book-of-shadows-print-cover-v1\.webp"/);
 assert.match(html,/await Promise\.all\(Array\.from\(el\.querySelectorAll\("img"\),img=>img\.decode\(\)\)\)/);
});
function fn(name){const start=html.indexOf('function '+name+'('),rest=html.slice(start),next=rest.slice(1).search(/\n(?:async )?function /);return next<0?rest:rest.slice(0,next+1)}
function context(s){const els={journalPrint:{},traditionsPrint:{},journalBookStatus:{},grimoireBookStatus:{}};const ctx=vm.createContext({KeepsakeBooks:books,localStorage:s,document:{getElementById:id=>els[id]},esc:x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),bookCover:title=>'<h1>'+title+'</h1>',divider:title=>'<h2>'+title+'</h2>',wheelRank:()=>0});for(const name of ['shadowsCover','bookText','buildJournalBook','buildCelebrationsBook'])vm.runInContext(fn(name),ctx);return {ctx,els}}
test('both books render all source entries, escape notes and preserve line breaks',()=>{let s=fixture();s.setItem('cw-calendar',JSON.stringify([{d:'2026-10-08',text:'<script>\nNext'}]));let {ctx,els}=context(s);assert.equal(ctx.buildJournalBook(),true);assert.match(els.journalPrint.innerHTML,/&lt;script&gt;<br>Next/);assert.match(els.journalPrint.innerHTML,/Moon notes/);assert.match(els.journalPrint.innerHTML,/The Star/);assert.equal(ctx.buildCelebrationsBook(),true);assert.match(els.traditionsPrint.innerHTML,/My Book of Shadows/);assert.match(els.traditionsPrint.innerHTML,/Full Moon/)});
test('book assembly blocks printing instead of silently omitting corrupt sources',()=>{let s=fixture();s.setItem('cw-moon-entries','bad');let {ctx,els}=context(s);assert.equal(ctx.buildJournalBook(),false);assert.equal(els.journalPrint.innerHTML,'');assert.match(els.journalBookStatus.textContent,/printing is paused/)});
function tarotUI(s){const els={tarotJournalStatus:{},tarotEntries:{}};for(const k of ['date','card','first','journal','meaning'])els[k]={value:s.getItem('cw-tarot-'+k)||''};const ctx=vm.createContext({KeepsakeBooks:books,localStorage:s,document:{getElementById:id=>els[id],querySelector:selector=>els[selector.match(/tarot-(\w+)/)[1]]},esc:x=>String(x??'')});for(const name of ['bookText','tarotDraft','saveTarotEntry','newTarotEntry','editTarotEntry','renderTarotEntries'])vm.runInContext(fn(name),ctx);return {ctx,els}}
test('legacy Tarot draft is preserved on read, explicitly saved, then cleared only after starting a new entry',()=>{const s=storage({'cw-tarot-date':'2026-10-08','cw-tarot-card':'Star','cw-tarot-journal':'Old reflection'}),{ctx,els}=tarotUI(s);ctx.renderTarotEntries();assert.equal(els.journal.value,'Old reflection');assert.equal(books.readTarot(s).length,0);ctx.newTarotEntry();assert.equal(books.readTarot(s)[0].journal,'Old reflection');assert.equal(els.journal.value,'')});
test('new Tarot entry aborts when saving fails and keeps the draft intact',()=>{const s=storage({'cw-tarot-date':'2026-10-08','cw-tarot-journal':'Keep me'}),{ctx,els}=tarotUI(s);s.setItem=()=>{throw Error('Quota')};ctx.newTarotEntry();assert.equal(els.journal.value,'Keep me');assert.equal(s.getItem('cw-tarot-journal'),'Keep me');assert.match(els.tarotJournalStatus.textContent,/preserved/)});
test('editing another Tarot entry first saves the current draft and avoids duplicate saved copies',()=>{const s=storage({'cw-tarot-entries':[{id:'old',d:'2026-10-07',card:'Sun',journal:'Earlier'}],'cw-tarot-date':'2026-10-08','cw-tarot-journal':'New draft'}),{ctx,els}=tarotUI(s);ctx.editTarotEntry(0);assert.equal(books.readTarot(s).length,2);assert.equal(els.journal.value,'Earlier');els.journal.value='Edited';ctx.saveTarotEntry();assert.equal(books.readTarot(s).length,2);assert.equal(books.readTarot(s).find(x=>x.id==='old').journal,'Edited');ctx.editTarotEntry(books.readTarot(s).findIndex(x=>x.id==='old'));assert.equal(els.journal.value,'Edited')});
